<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="zadaci.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="style.css" />
    <Content Include="zadaci.html" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Program.cs" />
  </ItemGroup>

</Project>
